default_language_version:
    python: python3.10
exclude: ^cc/idl/.*$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: ["--markdown-linebreak-ext=md"]
    exclude: .gitignore
  - id: mixed-line-ending
    args: ["--fix=auto"]
    exclude: .gitignore
  - id: check-merge-conflict
  - id: check-xml
  - id: debug-statements
  - id: check-executables-have-shebangs
  - id: check-symlinks

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: ["-w"]
    files: \.(md|bazel|py|c|h|cpp|hpp|txt|yaml|yml|sh|bzl)$


- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint
    args: [-s]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args: [--line-length=120]

- repo: https://github.com/tcort/markdown-link-check
  rev: v3.10.0
  hooks:
  - id: markdown-link-check
    args: ["--config", ".markdown_link_check_config.json"]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: 
    - --profile=black


