#!/bin/bash

set -euo pipefail

if [[ -z "${BUILD_BUDDY_API_KEY:-}" ]]; then
  BUILD_BUDDY_API_KEY=$(git config buildbuddy.api-key)
fi

echo '{
  "headers": {
    "x-buildbuddy-api-key": ["'"${BUILD_BUDDY_API_KEY}"'"]
  }
}'
