name: Run tasks

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests targeting main branch

jobs:
  build:
    runs-on: [self-hosted, X64, Linux]
    strategy:
      matrix:
        task: [
          ./run py-test, 
          ./run py-cov,
          ./run cc-integ-test,
          ./run cc-tar
        ]
      fail-fast: true

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt install -y lcov &&
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.23.0/bazelisk-amd64.deb &&
          sudo dpkg -i bazelisk-amd64.deb &&
          which bazelisk

      # Run tasks
      - name: Run tests
        run: {{ matrix.task }}
